
version: '3.5'

services:
  mariadb:
    # image : mariadb:10.3.13
    build: requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: 
      - .env
    # ports:
    #   - "3306:3306"
    volumes: 
      - dbdata:/var/lib/mysql
    # command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress: 
    depends_on: 
      - mariadb
    # image: wordpress:5.1.1-fpm-alpine
    build: requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: 
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  nginx:
    depends_on:
      - wordpress
    build: requirements/nginx/
    env_file :
      - .env
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      # - ./requirements/nginx/conf:/etc/nginx/conf.d
    networks:
      - app-network


volumes:
  wordpress:
  dbdata:

# volumes:
#   wordpress:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       # device: /Users/antoine/Documents/Data/wordpress
#       device: /local-home/amouly/goinfre/data/wp5
#   dbdata:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       # device: /Users/antoine/Documents/Data/mariadb
#       device: /local-home/amouly/goinfre/data/db5    

networks:
  app-network:
    driver: bridge

    