
version: '3'

services:
  mariadb:
    image : mariadb:10.3.13
    # build: requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes: 
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on: 
      - mariadb
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    ports:
      - "9000:9000"
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    links:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  nginx:
    depends_on:
      - wordpress
    build: requirements/nginx/
    container_name: nginx
    restart: unless-stopped
    ports:
      - "6500:6500"
      - "6556:6556"
    volumes:
      - wordpress:/var/www/html
      # - ./requirements/nginx/conf:/etc/nginx/conf.d
    networks:
      - app-network


# volumes:
#   wordpress:
#   dbdata:

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      # device: /Users/antoine/Documents/Data/wordpress
      device: /local-home/amouly/Documents/Data/wordpress
  dbdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      # device: /Users/antoine/Documents/Data/mariadb
      device: /local-home/amouly/Documents/Data/mariadb    

networks:
  app-network:
    driver: bridge

    